using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ReadAndVerify
{
    /// <summary>
    /// Логика взаимодействия для UpdateData.xaml
    /// </summary>
    public partial class UpdateData : Window
    {
        public UpdateData()
        {
            InitializeComponent();
        }

        List<Project> projects = new List<Project>();

        public UpdateData(List<Project> projects)
        {
            InitializeComponent();
            DataContext = this;
            this.projects = projects;
            dGrid.ItemsSource = projects;
        }

        private void dGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            try
            {
                //MessageBox.Show(e.PropertyType.ToString());
                if (e.PropertyType.Name == "DateTime")
                {
                    e.Column.Header = "DateTime";
                }
            }
            catch {  }

        }

        private void dGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            
        }
    }
}
